# Create netlify.toml in frontend directory
cat > frontend/netlify.toml << EOL
[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/*"
  to = "https://your-backend-url.onrender.com/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
EOL

# Commit and push the new file
git add frontend/netlify.toml
git commit -m "Add Netlify configuration"
git push